# Generated by Django 5.2.8 on 2025-11-23 09:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('N', 'North'), ('NE', 'North-East'), ('E', 'East'), ('SE', 'South-East'), ('S', 'South'), ('SW', 'South-West'), ('W', 'West'), ('NW', 'North-West')], max_length=2)),
                ('distance', models.IntegerField(help_text='Distance in nautical miles (must be positive)', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(help_text='Details about landmarks or hazards')),
                ('risk_level', models.IntegerField(help_text='Risk level from 0 (safe) to 100 (deadly)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('previous_instruction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_step', to='compass.instruction', verbose_name='Previous Instruction')),
            ],
        ),
    ]
